# Generated by Django 4.0.6 on 2022-07-05 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_song_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='song_link',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Автор'),
        ),
    ]
