# Generated by Django 4.0.6 on 2022-07-05 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_song_song_link'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Song',
        ),
    ]
