# Generated by Django 4.0.6 on 2022-07-05 19:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_delete_song'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(blank=True, max_length=30, null=True, verbose_name='Автор')),
                ('song_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='название песни')),
                ('lyrics', models.TextField(blank=True, max_length=500, null=True, verbose_name='Текст песни')),
                ('song_link', models.CharField(blank=True, max_length=30, null=True, verbose_name='Автор')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'ordering': ['-song_name'],
            },
        ),
    ]
