# Generated by Django 4.0.6 on 2022-07-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_song_song_link_alter_song_song_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='song',
            options={'ordering': ['song_name']},
        ),
    ]
